### PR TITLE
Fixed building errors for nginx v1.11.6 and changed dash scheme url t…

### PR DESCRIPTION
**Pull request by akotulu**
Nginx 1.11.6 wont compile.

Nowaday https is prefered.
https://vm2.dashif.org/dash/time.txt

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
Please, don't create merge requests against master branch. Use `dev` branch.
And why you think that `UTCTiming` tag is invalid?

**Comment by akotulu** [comment]
When I removed UTCTiming, Dash.js started to work. I'm bit confused here. I tried original repo and it didn't work with Dash.js. Then I found your repo, it worked but at showed only first frames and hanged. So I started to investigate, ran the mpd against validator, it told that UTCTiming is invalid, so I removed it and stream started to play. Now it plays for 10min and then no stream can be picked up. I have no clue whats wrong. Is it dash.js error or something else. I need to stream video from Raspberry pi to my external server and display it in web browser. Tried hls, but it only plays on Safary, but I need Chrome or Firefox aswell.

**Comment by lpcollier** [comment]
I have HLS working fine cross-browser and cross-device including Chrome and Firefox (and even IE on Windows 7...).  I'm using Flowplayer, which plays HLS natively on Safari and iOS devices, and wraps hls.js on other platforms.

The main issue I encountered is that hls.js relies on a different cross-domain security setup than the native HLS player.  You need to put directives in to add CORS (http://enable-cors.org) headers to the http location used for your HLS playlists.

If you've got a working HLS setup and your issue is getting clients working then I'm happy to help out or give you a copy of my config file.

**Comment by akotulu** [comment]
Thank you for suggesting Flowplayer, got it working 👍

**Comment by sergey-dryabzhinsky** [comment]
Done in #198

**Comment by sergey-dryabzhinsky** [comment]
If you are using `dev` branch - check new directives for DASH - https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/dev/doc/README.md

**Pull request closed without merging**
