### PR TITLE
MOD move wiki to /docs

### PR DESCRIPTION
**Pull request by jstabenow**
Documentation by the wiki is a little bit tricky because no one can see the changes. That's why I moved the wiki to /docs. Hope it's an good idea.

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
File ```doc/README.md``` seems missing.

**Comment by jstabenow** [comment]
Whoops, sorry! Have they added

**Comment by sergey-dryabzhinsky** [comment]
Cool! Thank you!

**Comment by jstabenow** [comment]
No, thanks for your fork! :-) It's awesome

**Pull request merged**
