### PR TITLE
Improved MPEG-TS stream descriptions

### PR DESCRIPTION
**Pull request by premultiply**
Hopefully it helps to better understand magic MPEG-TS byte patterns for further modifications and bugfixes

### CODE REVIEW

**Comment by chriswiggins** [comment]
Thanks @premultiply. Does this still work if you send in only video or only audio?

@sergey can I please test this in a few different scenarios before you merge?

**Comment by premultiply** [comment]
I think think the code in ngx_rtmp_mpegts.c should be optimized to allow for a dynamic but valid TS generation. Maybe it would be a better idea not to pre-calculate things like crc and length values and try to patch them later by code. Instead the PMT descriptors should always be added by code dependent on the type and count of input elementary streams for example.

I am not able to do such "major" code modifications in C by myself but I can assist with all MPEG-TS related stuff and validation of it.

**Comment by sergey-dryabzhinsky** [comment]
@chriswiggins Of cause you can. I'm in no hurry.

**Comment by chriswiggins** [comment]
@premultiply just looking over this now, are you able to provide a TS header example for when there's only h.264 video? (i.e no audio in the payload)

I'm trying to understand how this changes PMTs etc and am happy to work with you to refactor this in properly and make the CRC generation dynamic

**Comment by premultiply** [comment]
Shure. And thanks for support in fixing it.
I will try it in words first:

The main difference is the component loop in PMT. Just add oder kick components (5 bytes) in relation what is contained in the TS stream. Of course you have to make shure that the section_length in PMT is correctly written. section_length is the bytecount starting at the byte after the section_length-field up to the last byte of PMT (last byte of crc in this case).

What is also important is the PCR_PID field in PMT which points to the PID with the timing information. In normal cases the PCR it is part of Video-PID but can also be in Audio-PID or in a separate PCR-PID.

**Comment by chriswiggins** [comment]
Hi @premultiply - thanks for the description it has been very helpful. I've done lots of refactoring of the code to make it more extendible in the future.

I can't dynamically calculate the CRC however because each time I do I seem to get an invalid value. From where do we need to calculate the PMT CRC? From `0x47` to the last byte before the CRC entry?

Thanks for helping with this

**Comment by premultiply** [comment]
CRC has to be calculated from first byte of MPEG-Table (only PMT or PAT in our case) to the last byte before CRC value itself. First byte of table means table_id(8) field.

And you have to make shure that you use the correct CRC32-MPEG2 implementation.

**Comment by chriswiggins** [comment]
OK, I'm using `pycrc` with the `crc-32-mpeg` model but its not producing the same results as `tstools` which is telling me the CRC is wrong :-(

**Comment by premultiply** [comment]
A working VB6.0 code looks like this. Should be easy to convert.

```
Private crc32_table(0 To 255) As Long
Private crc32_mpeg2_table_created As Boolean

Private Sub crc32_create_table()
    Dim i As Long, j As Long, k As Long
    For i = 0 To 255
        k = 0
        j = ShiftLeft(i, 24) Or &H800000
        While j <> &H80000000
            k = ShiftLeft(k, 1) Xor IIf(((k Xor j) And &H80000000), &H4C11DB7, 0)
            j = ShiftLeft(j, 1)
        Wend
        crc32_table(i) = k
    Next i
    crc32_mpeg2_table_created = True
End Sub

Private Function crc32_mpeg2_calc(data() As Byte) As Long
    If Not crc32_mpeg2_table_created Then crc32_create_table
    Dim i As Long, i_crc As Long
    i_crc = &HFFFFFFFF
    For i = LBound(data) To UBound(data)
        i_crc = ShiftLeft(i_crc, 8) Xor crc32_table((ShiftRight(i_crc, 24) Xor data(i)) And &HFF)
    Next i
    crc32_mpeg2_calc = i_crc
End Function
```

**Comment by sergey-dryabzhinsky** [comment]
@chriswiggins Any news? How testing are going?

**Comment by chriswiggins** [comment]
@sergey-dryabzhinsky I've just completed this on my branch (dynamic CRC generation) - I will submit a pull request for it shortly but for now this one can be closed.

@premultiply thank you so much for the work you've done it really helped me understand the TS structures.

**Comment by premultiply** [comment]
Done by #228

**Pull request closed without merging**
