### PR TITLE
MPEG TS improvements

### PR DESCRIPTION
**Pull request by premultiply**
- Changed PMT PID to widely used 0x0FFF (4095) in HLS streams
- Write PCR on every frames (for hardware decoders and other DVB compatible decoders)
- Recalculated PAT CRC32

TODO: Recalculate PMT CRC32

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
It doesn't break Safari/iOS browsers?

**Comment by premultiply** [comment]
No, works fine.
There could and should be done more improvements like shorter PAT and PMT (<= 500ms) repetition intervals as but this needs further code investigation. Biggest problem was the PCR repetition interval.

**Comment by sergey-dryabzhinsky** [comment]
Thanks!

**Comment by premultiply** [comment]
Here are the updated CRCs for PMT:

line 75:
0x4e, 0x59, 0x3d, 0x1e, /* crc for mp3 */

line 81:
0x2f, 0x44, 0xb9, 0x9b, /* crc for aac */

Can you please change them?


An online calculator can be found here:
http://www.sunshine2k.de/coding/javascript/crc/crc_js.html
CRC32_MPEG2

**Comment by sergey-dryabzhinsky** [comment]
line 81 are the same.
line 75 i'll update.

**Comment by sergey-dryabzhinsky** [comment]
Done in https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/commit/b6687d6cab567acbbe02b7ed957b83323faed571

**Pull request merged**
