### PR TITLE
MPEG-DASH manifest generations update

### PR DESCRIPTION
**Pull request by ArhiChief**
Hi.

It was an issues with Google's shaka-player (https://github.com/google/shaka-player/issues/345). To resolve it I added **UTCTiming** element to force player to synchronize time with streaming server.

### CODE REVIEW

**Comment by sergey-dryabzhinsky** [comment]
You shouldn't remove ```availabilityEndTime``` cos ```type="dynamic"```.
This property must be set cos playlist time-limited.

**Comment by sergey-dryabzhinsky** [comment]
And you can't trust this ```if (publish_time[0] == '\0'){``` code cos it's compiler dependent.

**Comment by ArhiChief** [comment]
>This property must be set cos playlist time-limited.

As I understand (A.3.4 of ISO/IEC 23009-1:2014) **availabilityEndTime** could be calculated from **availabilityStartTime** and Timeline, so, this element is not necessary.

**Comment by sergey-dryabzhinsky** [comment]
I hope that change don't kill other DASH players.

**Comment by arition** [comment]
I believe this kill dash.js. dash.js doesn't work on the current master branch, but dash.js works on v1.1.7.10.

**Comment by ArhiChief** [comment]
Yeah. I create this patch to make work MPEG-DASH on Google's Shaka Player when my users had incorrect system time. It's also works on 2.0.0 of dash.js too.

**Comment by sergey-dryabzhinsky** [comment]
@arition can you try code from ```fix-121-dash-availabilityEndTime``` branch?

**Comment by sergey-dryabzhinsky** [comment]
@ArhiChief you too, please

**Comment by arition** [comment]
I test the ```fix-121-dash-availabilityEndTime``` branch, but seems that it still doesn't work using 2.1.1 version of dash.js.

**Comment by arition** [comment]
Sample mainfest generated from the ```fix-121-dash-availabilityEndTime``` branch
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2016-05-23T17:20:31-04:00"
    availabilityEndTime="2016-05-23T17:25:57-04:00"
    publishTime="2016-05-23T17:20:31-04:00"
    minimumUpdatePeriod="PT5S"
    minBufferTime="PT5S"
    timeShiftBufferDepth="P0Y00M00DT0H00M49.17S"
    suggestedPresentationDelay="PT10S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014"
       value="http://vm2.dashif.org/dash/time.txt" />  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="24000/1001">
      <Representation
          id="test_H264"
          mimeType="video/mp4"
          codecs="avc1.64001f"
          width="1280"
          height="720"
          frameRate="24000/1001"
          sar="1:1"
          startWithSAP="1"
          bandwidth="520824">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4v"
            initialization="test-init.m4v">
          <SegmentTimeline>
             <S t="277151" d="10594"/>
             <S t="287745" d="8968"/>
             <S t="296713" d="5213"/>
             <S t="301926" d="6340"/>
             <S t="308266" d="12179"/>
             <S t="320445" d="5881"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="test_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          startWithSAP="1"
          bandwidth="94695">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4a"
            initialization="test-init.m4a">
          <SegmentTimeline>
             <S t="277151" d="10594"/>
             <S t="287745" d="8968"/>
             <S t="296713" d="5213"/>
             <S t="301926" d="6340"/>
             <S t="308266" d="12179"/>
             <S t="320445" d="5881"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by arition** [comment]
Sample mainfest generated from ```1.1.7.10```
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2016-05-23T17:38:30-04:00"
    availabilityEndTime="2016-05-23T17:40:09-04:00"
    minimumUpdatePeriod="PT5S"
    minBufferTime="PT5S"
    timeShiftBufferDepth="P0Y00M00DT0H00M51.67S"
    suggestedPresentationDelay="PT10S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="24000/1001">
      <Representation
          id="test_H264"
          mimeType="video/mp4"
          codecs="avc1.64001f"
          width="1280"
          height="720"
          frameRate="24000/1001"
          sar="1:1"
          startWithSAP="1"
          bandwidth="520824">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4v"
            initialization="test-init.m4v">
          <SegmentTimeline>
             <S t="47881" d="7257"/>
             <S t="55138" d="12137"/>
             <S t="67275" d="7716"/>
             <S t="74991" d="6006"/>
             <S t="80997" d="5964"/>
             <S t="86961" d="12596"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="test_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          startWithSAP="1"
          bandwidth="94695">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4a"
            initialization="test-init.m4a">
          <SegmentTimeline>
             <S t="47881" d="7257"/>
             <S t="55138" d="12137"/>
             <S t="67275" d="7716"/>
             <S t="74991" d="6006"/>
             <S t="80997" d="5964"/>
             <S t="86961" d="12596"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

```

**Comment by sergey-dryabzhinsky** [comment]
Yeah.
Seems like ```availabilityEndTime``` not used in recent standard or I just not found it.
And Wowza not using ```publishTime``` for live streams.

**Comment by sergey-dryabzhinsky** [comment]
Similar issue I think: https://github.com/Dash-Industry-Forum/dash.js/issues/1366

And it seems we need to update ```publishTime```:
> specifies the wall-clock time when the MPD was generated and published at the origin server. MPDs with a later value of @publishTime shall be an update as defined in 5.4 to MPDs with earlier @publishTime.

Because MPD updates constantly.

**Comment by sergey-dryabzhinsky** [comment]
@arition can you try latest code from ```fix-121-dash-availabilityEndTime``` branch again?

**Comment by sergey-dryabzhinsky** [comment]
And probably ```availabilityStartTime``` should change only then segment deleted from list.

**Comment by arition** [comment]
the latest ```fix-121-dash-availabilityEndTime``` branch still not works

**Comment by arition** [comment]
latest mainfest file
```
<?xml version="1.0"?>
<MPD
    type="dynamic"
    xmlns="urn:mpeg:dash:schema:mpd:2011"
    availabilityStartTime="2016-05-23T18:32:08-04:00"
    publishTime="2016-05-23T18:32:08-04:00"
    minimumUpdatePeriod="PT5S"
    minBufferTime="PT5S"
    timeShiftBufferDepth="P0Y00M00DT0H00M53.21S"
    suggestedPresentationDelay="PT10S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011"
    xmlns:xsi="http://www.w3.org/2011/XMLSchema-instance"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd">
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014"
       value="http://vm2.dashif.org/dash/time.txt" />
  <Period start="PT0S" id="dash">
    <AdaptationSet
        id="1"
        segmentAlignment="true"
        maxWidth="1280"
        maxHeight="720"
        maxFrameRate="24000/1001">
      <Representation
          id="test_H264"
          mimeType="video/mp4"
          codecs="avc1.64001f"
          width="1280"
          height="720"
          frameRate="24000/1001"
          sar="1:1"
          startWithSAP="1"
          bandwidth="520824">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4v"
            initialization="test-init.m4v">
          <SegmentTimeline>
             <S t="369077" d="6840"/>
             <S t="375917" d="5881"/>
             <S t="381798" d="8717"/>
             <S t="390515" d="8049"/>
             <S t="398564" d="13514"/>
             <S t="412078" d="10218"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet
        id="2"
        segmentAlignment="true">
      <AudioChannelConfiguration
          schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011"
          value="1"/>
      <Representation
          id="test_AAC"
          mimeType="audio/mp4"
          codecs="mp4a.40.2"
          audioSamplingRate="44100"
          startWithSAP="1"
          bandwidth="94695">
        <SegmentTemplate
            presentationTimeOffset="0"
            timescale="1000"
            media="test-$Time$.m4a"
            initialization="test-init.m4a">
          <SegmentTimeline>
             <S t="369077" d="6840"/>
             <S t="375917" d="5881"/>
             <S t="381798" d="8717"/>
             <S t="390515" d="8049"/>
             <S t="398564" d="13514"/>
             <S t="412078" d="10218"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by arition** [comment]
Seems that dash.js is keeping visit ```http://vm2.dashif.org/dash/time.txt```, is that related to the issue?

**Comment by sergey-dryabzhinsky** [comment]
Oh, crap. It's emulates NTP requests by getting date from HTTP header.

**Comment by sergey-dryabzhinsky** [comment]
URL should refer to MPD itself. Or some static file on server. And it should be optional.

**Comment by arition** [comment]
Seems that the problem is related to
```
  <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-head:2014"
       value="http://vm2.dashif.org/dash/time.txt" />
```
I just comment these two lines and recompile the ```fix-121-dash-availabilityEndTime``` branch, then dash.js works fine

**Comment by sergey-dryabzhinsky** [comment]
Just updated branch.
Added two new options related to ```UTCTiming```. By default generation of this tag now ```off```.
By changed generation of ```availabilityStartTime``` and ```publishTime```.

@arition can you check it again?
@ArhiChief I'll wait for update from you too.

**Comment by arition** [comment]
In the latest version the ```availabilityStartTime``` start to change, and seems that caused some issues.
According to #48 the availabilityStartTime should not change after start.

**Comment by sergey-dryabzhinsky** [comment]
As I understand standard - ```availabilityStartTime``` is just starting time for all other times in playlist.

Then I try to play MPD via MP4Client - it warns about time drift:
```
[DASH] Slight drift in UTC clock at time 2016-05-24T10:53:01Z: diff AST - now 10787809 ms
```
I think it's because nginx-rtmp uses local time in playlist. It should be GMT.

**Comment by sergey-dryabzhinsky** [comment]
But in nginx-rtmp fragments time counting from stream start time. So you are right.
```availabilityStartTime``` must not change.

**Comment by sergey-dryabzhinsky** [comment]
@arition , reverted ```availabilityStartTime``` changes, add GMT times, msec granularity.
Can you check it again with dash.js?

**Comment by arition** [comment]
This time it works fine with default configs.
I have not test for ```UTCTiming```.

**Comment by sergey-dryabzhinsky** [comment]
```UTCTiming``` is needed to resync time difference between client and server.
Recommended value is ```dash_clock_compensation ntp;```.
But it can force sync via ```Date``` HTTP header by downloading static file defined in ```@value``` attribute:
```
dash_clock_compensation http_head;
dash_clock_helper_uri http://your-rtmp-server/time.txt;
```
And you need to force expire of that file:
```
# HTTP virt-host config

location /time.txt {
  expire -1;
  open_file_cache off;
}
```

**Pull request merged**
